version: '3.8'

services:
  web:
    image: team-profile-server:latest
    ports:
      - "80:3000"
  db:
    image: students-db:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fcds24